defaults: 
  - _self_

hydra:
  run:
    dir: outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}

root_path: "/mnt/sherlock/oak/prescribed_data"
save_path: "${root_path}/processed"
data_path: "${root_path}/raw"
template: "${root_path}/geoms/templates/template.tif"
mask: "${root_path}/geoms/california_geom/datacalifornia_geom.shp"
mtbs_shapefile: "${root_path}/geoms/mtbs_perims_DD_updated/mtbs_perims_DD.shp"