defaults:
  - _self_
  - compute: linux_machine
  - data: default
  - optim: small_grid
  - tyra: mtbs_treats
  - crs: "EPSG:3310"

hydra:
  run:
    dir: outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}