defaults:
  - _self_
  - compute: linux_machine
  - balancing: spillovers
  - data: default
  - build: mtbs
  - optim: small_grid
  - tyra: mtbs_treats

config: "EPSG:3310"

hydra:
  run:
    dir: outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}